Description: 'Amazon EKS Cluster Role'


Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String


Resources:

  eksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess

  CapstoneEKS:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.17"
      RoleArn: !GetAtt eksClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${EnvironmentName}-SCG"
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${EnvironmentName}-PUB-NETS
Outputs:
  EksId:
    Description: The EKS id.
    Value: !Ref CapstoneEKS
    Export:
      Name: !Sub ${EnvironmentName}-EKS

  EKSRoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt eksClusterRole.Arn
    Export:
      Name: !Sub "${EnvironmentName}-EKSRoleArn"
