# hello-kubernetes.yaml
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
  selector:
    app: streamlit-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: gradjitta/streamlit-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501